### ISSUE TITLE
Use Map or Object as an alternative to Array

### ISSUE THREAD

**Issue by helderjbe** [forwardemail/reserved-email-addresses-list#3]
This is a request to ship a js Map or js Object along with/instead of the array version.

The lookup on the Map/Object is O(1) while array is O(n). When checking upon signups and signins, this makes a difference when there are many requests per second.

Thanks.

**Comment by niftylettuce** [comment]
PR welcome

**Comment by niftylettuce** [comment]
Would love to have a PR for this!
