### ISSUE TITLE
Add PEC to reserved addresses

### ISSUE THREAD

**Issue by collimarco** [forwardemail/reserved-email-addresses-list#7]
PEC is the Italian official certified email address. Many official email addresses are `pec@example.com`.

https://en.wikipedia.org/wiki/Certified_email

I think that it would be useful to add it to the list.

**Comment by titanism** [comment]
Will do, one moment

**Comment by titanism** [comment]
https://github.com/forwardemail/reserved-email-addresses-list/releases/tag/v2.0.13

**Comment by titanism** [comment]
v2.0.13 released to npm, thanks @collimarco 🙏
